In [5]:
from tensorflow.keras.preprocessing.text import one_hot 

In [2]:
## sentences
sent = [
    "the glass of milk",
    "the glass of juice",
    "the cup of tea",
    "I am a good boy",
    "I am a good developer",
    "understand the meaning of words",
    "your videos are good"
]

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [3]:
## Define the vocabulary size
voc_size = 10000

In [6]:
### one hot representation
one_hot_repr = [one_hot(words, voc_size) for words in sent]


In [7]:
one_hot_repr

[[690, 7995, 3141, 5951],
 [690, 7995, 3141, 1535],
 [690, 2549, 3141, 8385],
 [5513, 7507, 3744, 88, 4028],
 [5513, 7507, 3744, 88, 4375],
 [4296, 690, 12, 3141, 150],
 [4500, 8885, 1942, 88]]

In [10]:
for i, words in enumerate(sent):
    print(words)
    print(one_hot_repr[i])
    print()

the glass of milk
[690, 7995, 3141, 5951]

the glass of juice
[690, 7995, 3141, 1535]

the cup of tea
[690, 2549, 3141, 8385]

I am a good boy
[5513, 7507, 3744, 88, 4028]

I am a good developer
[5513, 7507, 3744, 88, 4375]

understand the meaning of words
[4296, 690, 12, 3141, 150]

your videos are good
[4500, 8885, 1942, 88]



In [13]:
## word embedding representation

from tensorflow.keras.layers import Embedding
# from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences

In [14]:
import numpy as np

In [15]:
sent_length = 8

In [36]:
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)

In [37]:
embedded_docs

array([[   0,    0,    0,    0,  690, 7995, 3141, 5951],
       [   0,    0,    0,    0,  690, 7995, 3141, 1535],
       [   0,    0,    0,    0,  690, 2549, 3141, 8385],
       [   0,    0,    0, 5513, 7507, 3744,   88, 4028],
       [   0,    0,    0, 5513, 7507, 3744,   88, 4375],
       [   0,    0,    0, 4296,  690,   12, 3141,  150],
       [   0,    0,    0,    0, 4500, 8885, 1942,   88]], dtype=int32)

In [38]:
## feature representation
dim = 10

In [42]:
model = Sequential()

model.add(Embedding(voc_size, dim, input_length=sent_length))

model.compile('adam', 'mse')

/Users/rahulshelke/Documents/Data-Science/Data-Science-Projects/Complete-Generative-AI-Course-With-Langchain-and-Huggingface/venv/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [43]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [45]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step


array([[[-3.78515609e-02,  3.46685573e-03,  5.15259802e-04,
         -3.95979173e-02,  3.75332572e-02, -1.34909861e-02,
          2.99861915e-02, -4.42267656e-02,  4.75619100e-02,
          2.68541239e-02],
        [-3.78515609e-02,  3.46685573e-03,  5.15259802e-04,
         -3.95979173e-02,  3.75332572e-02, -1.34909861e-02,
          2.99861915e-02, -4.42267656e-02,  4.75619100e-02,
          2.68541239e-02],
        [-3.78515609e-02,  3.46685573e-03,  5.15259802e-04,
         -3.95979173e-02,  3.75332572e-02, -1.34909861e-02,
          2.99861915e-02, -4.42267656e-02,  4.75619100e-02,
          2.68541239e-02],
        [-3.78515609e-02,  3.46685573e-03,  5.15259802e-04,
         -3.95979173e-02,  3.75332572e-02, -1.34909861e-02,
          2.99861915e-02, -4.42267656e-02,  4.75619100e-02,
          2.68541239e-02],
        [ 1.62559263e-02,  5.72906807e-03,  4.86465953e-02,
          4.56974991e-02,  2.80564465e-02, -3.61938477e-02,
         -2.94031743e-02, -2.65562776e-02, -2.571593

In [46]:
embedded_doc[0]

array([   0,    0,    0,    0,  690, 7995, 3141, 5951], dtype=int32)

In [47]:
embedded_doc.shape

(7, 8)

In [49]:
model.predict(embedded_doc[[[0]][0]])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step


array([[[-0.03785156,  0.00346686,  0.00051526, -0.03959792,
          0.03753326, -0.01349099,  0.02998619, -0.04422677,
          0.04756191,  0.02685412],
        [-0.03785156,  0.00346686,  0.00051526, -0.03959792,
          0.03753326, -0.01349099,  0.02998619, -0.04422677,
          0.04756191,  0.02685412],
        [-0.03785156,  0.00346686,  0.00051526, -0.03959792,
          0.03753326, -0.01349099,  0.02998619, -0.04422677,
          0.04756191,  0.02685412],
        [-0.03785156,  0.00346686,  0.00051526, -0.03959792,
          0.03753326, -0.01349099,  0.02998619, -0.04422677,
          0.04756191,  0.02685412],
        [ 0.01625593,  0.00572907,  0.0486466 ,  0.0456975 ,
          0.02805645, -0.03619385, -0.02940317, -0.02655628,
         -0.02571594,  0.0008532 ],
        [-0.0439387 ,  0.00731028,  0.01162801,  0.02375242,
          0.02817495, -0.00280607, -0.04365983,  0.04276415,
         -0.01728443, -0.02870852],
        [ 0.00602263,  0.01513088, -0.02078449,  0.0